name: Verify CI
run-name: "Verify ${{ github.event.pull_request && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || format('`{0}` on {1}', github.event.head_commit.message, github.ref) }}"

on:
  pull_request:
    branches: [main]
  push:
  workflow_call:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm i
      - run: pnpm build
      - run: pnpm -r build
      - run: pnpm fmtcheck
      - run: echo 'Do you like green eggs and ham?'
